### Authentification for user

POST http://localhost:8180/auth/realms/quarkus/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_secret=0b2d1fcc-8b00-4f46-9bef-3ea7f99eb879&client_id=my-quarkus-service&username=john&password=passme&grant_type=password

> {%  client.global.set("access_token", response.body.access_token); %}


### Authentification for admin

POST http://localhost:8180/auth/realms/quarkus/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_secret=0b2d1fcc-8b00-4f46-9bef-3ea7f99eb879&client_id=my-quarkus-service&username=admin&password=passme&grant_type=password

> {%  client.global.set("access_token", response.body.access_token); %}



### get graphql scheme

GET http://localhost:8080/api/graphql/schema.graphql



### INGREDIENT

POST http://localhost:8080/api/ingredient
Authorization: Bearer {{access_token}}
Content-Type: application/json

  {
    "name": "Yuca",
    "comment": "Findet man hauptsächlich in Südamerika"
  }
### Create

PUT http://localhost:8080/api/ingredient/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

  {
    "name": "Mangold",
    "comment": "Findet man hauptsächlich in Südamerika"
  }
### Update

GET http://localhost:8080/api/ingredient
Authorization: Bearer {{access_token}}
Content-Type: application/json
### Get Qute html page

GET http://localhost:8080/api/ingredient/getAll
Authorization: Bearer {{access_token}}
Content-Type: application/json
### Find all

GET http://localhost:8080/api/ingredient/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
### Find certain

DELETE http://localhost:8080/api/ingredient/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
### Delete